- hosts: workers
  become: yes
  tasks:
    - name: Import Package Provisioning
      import_tasks: "install_packages.yml"

- name: import playbook
  import_playbook: "setup_server.yml"

- name: import playbook
  import_playbook: "setup_worker.yml"
