- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Install yum packages
      yum:
        name: "net-tools,git,tar"
        state: present

- name: import playbook
  import_playbook: "setup_worker.yml"
