- hosts: controller
  tasks:
    - name: import Package Provisioning
      import_tasks: "install_packages.yml"
- hosts: controller
  become: yes
  gather_facts: false
  environment:
    K3S_EXTERNAL_IP: "{{ hostvars['ccabral']['private_ip'] }}"
    INSTALL_K3S_EXEC: "--flannel-iface eth1 --no-deploy traefik"
  roles:
    - k3s
