- hosts: controller
  become: true
  gather_facts: false
  environment:
    K3S_EXTERNAL_IP: "{{ hostvars['ccabral']['private_ip'] }}"
    INSTALL_K3S_EXEC: "--flannel-iface eth1"
  roles:
    - k3s
  tasks:
    - name: Fetch config file
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./
        flat: true
    - name: Edit server IP in k3s.yaml
      become: false
      local_action:
        module: ansible.builtin.lineinfile
        line: '\1server: https://{{ hostvars["ccabral"]["private_ip"] }}:6443'
        path: "./k3s.yaml"
        regexp: "( *)server:.*"
        backrefs: yes
    - name: Add a repository
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami
    - name: Serve website
      become: true
      kubernetes.core.helm:
        update_repo_cache: true
        name: test
        binary_path: /usr/bin/helm
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        chart_ref: bitnami/nginx
        release_namespace: default
