- hosts: controller
  become: yes
  gather_facts: false
  roles:
    - k3s
  tasks:
    - name: Read node-token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: node_token_output
    - name: Add node_token to facts
      ansible.builtin.set_fact:
        cacheable: true
        node_token: "{{ node_token_output.stdout_lines[0] }}"
